### ISSUE TITLE
Mejorar vista topic con Rango

### ISSUE THREAD

**Issue by luarar** [datosgobar/consulta-publica#187]
Ajustar los estilos a los nuevos cambios de diseño.

- [x] No tiene que mostrarse el label "neutral".

- [x] Quitar alert "Ya votaste".

- [x] Modificar botón "Cambiar voto".

- [x] En rango cerrado ocultar num de participantes (se traen del componente base).

- [x] Quitar bordes.

- [x] Colocar alert "Tan pronto como finalice la consulta..."

- [x] Cuando se cierra debe aparecer el botón "Participá en otra consulta" que dirija a la Home.

**Comment by florlafuente** [comment]
La mejora del label neutral se soluciona en esta PR: https://github.com/DemocracyOS/democracyos/pull/1631
Cierro issue.
