### ISSUE TITLE
Mejorar componente Voto

### ISSUE THREAD

**Issue by luarar** [datosgobar/consulta-publica#198]
- [x] Cambiar colores de botones

- [x] Colocar alert "Gracias por...".

- [x] Agregar "Elegiste la opción "A favor/en contra/neutral"

- [x] Ocultar todos los "n votos contados".

- [x] Cambiar colores del gráfico.

- [x] Agregar botón "Participar en otra consulta".

**Comment by florlafuente** [comment]
Cambiar colores de grafico resuelto en DemocracyOS base: https://github.com/DemocracyOS/democracyos/pull/1632
Cierro issue.
