### ISSUE TITLE
Corregir links

### ISSUE THREAD

**Issue by franciclo** [datosgobar/consulta-publica#227]
- [x] El diseño propone que el autor en una consulta sea un link, por el momento no va a serlo, lo agregaríamos cuando esté listo el buscador para que redireccione a la home con el filtro por autor seteado.
- [x] En la vista del topic, las tags no deben ser cliqueables porque no está impementada la funcionalidad para fitlrar por etiquetas aún.

**Comment by slorenzo** [comment]
https://github.com/datosgobar/consulta-publica/commit/a39853b176641ad325ee1370769892521bcd7352
