### ISSUE TITLE
Home principal

### ISSUE THREAD

**Issue by Marienkafer** [datosgobar/consulta-publica#231]
Referencia: https://xd.adobe.com/view/09562a1d-0328-4e32-6318-a2f3224aa9d3-7f67/

- [x] Modificar copy de sección de onboarding, cambiar color en texto "Consulta Publica", modificar "permiten" por "permite"
Referencia:
![image](https://user-images.githubusercontent.com/11686457/44997614-21106080-af86-11e8-88cb-4172962dd0fd.png)

- [x] Call to action "quiero participar" hace scroll  down a las consultas, no redirecciona al ingreso, modificar la redirección

- [x] Aumentar un poco el tamaño el logo de consulta publica

- [x] Cambiar CTA en botón de header de Registrar a -> Ingresar

- [x]  El botón de "Ingresar" debe redirigir primero al login y desde el login se accede al registrarse 

- [x] Cambiar titulo de "Consultas" a "Conoce las consultas disponibles" 
![image](https://user-images.githubusercontent.com/11686457/44998695-e3173a80-af8d-11e8-8ccc-a2e3df20c75b.png)

**Comment by slorenzo** [comment]
https://github.com/datosgobar/consulta-publica/commit/0e9d08f2b0b565f5857310f8ff21d5cba3bd824f
