### ISSUE TITLE
Edición estilos home de consultas

### ISSUE THREAD

**Issue by Marienkafer** [datosgobar/consulta-publica#232]
- [ ] Modificar margenes y tamaño de texto al de poncho, actualmente el tamaño de fuente es muy grande, Mantener tamaño de imágenes y videos del texto enriquecido que ya está implementado.
Referencia: http://argob.github.io/poncho/ejemplos/pagina-area.html

- [x] Modificar  label de cantidad de ejes, no debe estar en mayúsculas
![image](https://user-images.githubusercontent.com/11686457/44998110-67b38a00-af89-11e8-81e8-1a321c3e52f8.png)

**Comment by slorenzo** [comment]
https://github.com/datosgobar/consulta-publica/commit/6ac52b6db74ee82cc6a1d62e8b09ba72dc6627ed
