### ISSUE TITLE
Tamaño de fuente en los ejes

### ISSUE THREAD

**Issue by Marienkafer** [datosgobar/consulta-publica#233]
- [ ] Mantener tamaño de la fuente de poncho del contenido y los comentarios, está muy pequeño
http://argob.github.io/poncho/ejemplos/noticia.html

**Comment by slorenzo** [comment]
https://github.com/datosgobar/consulta-publica/commit/0e9d08f2b0b565f5857310f8ff21d5cba3bd824f
